name: Deploy to Azure Static Web Apps

on:
  workflow_call:
    inputs:
      application:
        type: string
        required: true
      target:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ inputs.target }}
        run: echo $MESSAGE
