name: Flyway migrate test

on:
  workflow_call:
    inputs:
      flyway_script_locations:
        type: string
        required: true
      flyway_command:
        type: string
        required: false
        default: migrate
    secrets:
      mssql_sa_password:
        required: true

jobs:
  flyway:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    services:
      sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: ${{ secrets.mssql_sa_password }}
        options: >-
          --health-cmd "grep 'SQL Server is now ready for client connections.' /var/opt/mssql/log/errorlog"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run database init script
        run: sqlcmd -U sa -P ${{ secrets.mssql_sa_password }} -S localhost -Q "CREATE DATABASE test"
      - name: Run flyway command
        uses: docker://flyway/flyway
        env:
          FLYWAY_URL: jdbc:sqlserver://sql;database=test;encrypt=false;
          FLYWAY_USER: sa
          FLYWAY_PASSWORD: ${{ secrets.mssql_sa_password }}
          FLYWAY_LOCATIONS: 'filesystem:./${{ inputs.flyway_script_locations }}'
        with:
          args: ${{ inputs.flyway_command }}
