name: Deploy

on:
  workflow_call:
    inputs:
      application:
        type: string
        required: false
      environment:
        type: string
        required: true
      flyway_script_locations:
        type: string
        required: false
    secrets:
      azure_credentials:
        required: true
      tf_storage_account:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Apply Terraform configuration
        uses: kgknutsson/github-actions/gitops-apply-terraform@v1
        with:
          azure_credentials: ${{ secrets.azure_credentials }}
          tf_storage_account: ${{ secrets.tf_storage_account }}
          environment: ${{ inputs.environment }}
  deploy:
    needs: [terraform]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy a Java application to Azure App Service
        uses: kgknutsson/github-actions/gitops-deploy-to-app-service-java@v1
        with:
          azure_credentials: ${{ secrets.azure_credentials }}
  flyway:
    needs: [terraform]
    if: inputs.flyway_script_locations != ''
    runs-on: self-hosted
    steps:
      - name: Apply Flyway database migrations
        uses: kgknutsson/github-actions/gitops-sql-migrate-flyway@v1
        with:
          script-locations: ${{ inputs.flyway_script_locations }}
